# Generated by Django 4.0.6 on 2022-07-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
