# Generated by Django 4.0.6 on 2022-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
