# Generated by Django 4.0.6 on 2022-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_pub',
        ),
    ]
