# Generated by Django 4.0.6 on 2022-07-21 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_time_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_pub',
            field=models.DateTimeField(default=datetime.date(2022, 7, 21)),
        ),
    ]
